name: Generate iCal File Weekly

on:
  schedule:
    # Runs every Sunday at 05:00 AM
    - cron: '0 5 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: |
        poetry update

    - name: Run script to generate iCal file
      run: python create_ical.py

    - name: Sync to Gist using GitHub CLI
      env:
        GH_TOKEN: ${{ secrets.GIST_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        gh auth login --with-token <<< "$GH_TOKEN"
        gh gist edit "$GIST_ID" agenda.ics